### PR TITLE
Add support for author element search

### PR DESCRIPTION
**Pull request by Skullbock**
Added support in the old model for searching on the author of an item, either the author name or the user name.

### CODE REVIEW

**Comment by miljan-aleksic** [comment]
Can you tell me about this?

**Comment by Skullbock** [comment]
it was an old PR to allow to search on the author of an element

**Comment by miljan-aleksic** [comment]
I can see that, but it is something we needed what for? Still needed? Should we impelement it?

**Comment by Skullbock** [comment]
We'll reimplement it later on if needed

**Pull request closed without merging**
